var f=require('fs');
var c=f.readFileSync('public/index.html','utf8');
var txt="function pricePill(";
var i=c.indexOf(txt);
var n=c.indexOf('\r\n',i+1);
var line=c.substring(i,n);
console.log('pricePill line length:',line.length);
console.log('Last 30 chars:',JSON.stringify(line.substring(line.length-30)));
console.log('Has return:',line.indexOf("return'")>=0);
console.log('Has strong close:',line.indexOf("</strong>'+")>=0);
