var fs=require('fs');
var c=fs.readFileSync('public/index.html','utf8');
var i=c.indexOf('setTimeout(function ptr');
var j=c.indexOf('function initAll');
var oldBlock=c.substring(i,j);
var newBlock='var _ptrEl=document.getElementById(\"pullHint\"),_ptrBtn=document.getElementById(\"mobStatusBar\");if(_ptrEl&&_ptrBtn){_ptrBtn.style.cursor=\"pointer\";_ptrBtn.addEventListener(\"click\",function(){_ptrEl.style.display=\"block\";_ptrEl.innerHTML=\"⟳ 刷新中...\";refreshPrices().then(function(){_ptrEl.innerHTML=\"✅ 已刷新\";setTimeout(function(){_ptrEl.style.display=\"none\"},1000)})})}\r\n\r\n';
c=c.replace(oldBlock,newBlock);
fs.writeFileSync('public/index.html',c);
console.log('replaced old length',oldBlock.length,'with new length',newBlock.length);
console.log(c.includes('✅ 已刷新'));
