name = "wealth-tracker"
main = "src/worker.js"
compatibility_date = "2025-01-01"

[assets]
binding = "ASSETS"
directory = "public"

[[d1_databases]]
binding = "DB"
database_name = "wealth-db"
database_id = "f5ffd073-c0a2-4fad-a470-7f9120eae3d8"
